# Generated by Django 4.2 on 2023-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("post", models.TextField()),
                ("author", models.CharField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
